add logging
archio1/DetectFakeNews pull request #9
Opened 2022-10-12 14:25 UTC by archio1

2022-10-12 16:28 UTC, merseneries commented on src/FakeClass.py
>  parent_path = Path().resolve()
Add an empty line between imports and download

```python
from nltk.corpus import stopwords

nltk.download('stopwords')
parent_path = Path().resolve()
```

2022-10-12 16:35 UTC, merseneries commented on src/FakeClass.py
> +logging.basicConfig(format='%(asctime)s %(levelname)-8s %(message)s',
why do you use here `-8s` for `levelname`?

2022-10-12 16:50 UTC, merseneries requested changes
Three points from me:

1. Part of the code needs formatting. Install `black` package to format the code. 
2. Log messages don't have to be in every method, just the main ones.
3. Use the `present continuous` tense to write a message.

2022-10-13 16:25 UTC, archio1 commented on src/FakeClass.py
> +logging.basicConfig(format='%(asctime)s %(levelname)-8s %(message)s',
because i think about better fromation.

2022-10-13 16:28 UTC, merged

2022-10-13 16:28 UTC, merseneries commented
Good